---
- name: Install software
  dnf:
    name:
      - fish
    state: present

- name: Create fish directories
  file:
    path: "/home/{{ ansible_user }}/.config/fish/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: 0755
  with_items:
    - functions
    - completions

- name: Configure fish shell
  template:
    src: config.fish.j2
    dest: "/home/{{ ansible_user }}/.config/fish/config.fish"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Setup fish functions
  template:
    src: "{{ item }}.fish.j2"
    dest: "/home/{{ ansible_user }}/.config/fish/functions/{{ item }}.fish"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  with_items:
    - "fish_user_key_bindings"
    - "start_gutwin_services"

