---
- name: Setup Fedora Workstation
  hosts: localhost
  become: yes

  vars:
    user: jdudulski

  roles:
    - setup
    - gnome
    - neovim
    - elasticsearch
    - git
    - slack
    - flatpak
    - dropbox
