---
- name: Setup Fedora Workstation
  hosts: local
  become: yes

  roles:
    - role: setup
      tags:
        - setup
    - role: inputrc
      tags:
        - inputrc
    - role: nodejs
      tags:
        - nodejs
    - role: iosevka
      tags:
        - iosevka
        - fonts
        - devtools
    - gnome
    - role: neovim
      tags:
        - nvim
        - neovim
        - devtools
    - role: tilix
      tags:
        - tilix
    - role: elasticsearch
      tags:
        - elasticsearch
        - devtools
    - role: ruby
      tags:
        - ruby
        - devtools
    - role: git
      tags:
        - git
        - devtools
    - role: hashicorp
      tags:
        - hashicorp
    - role: postgres
      tags:
        - db
        - devtools
        - postgres
    - slack
    - role: docker
      tags:
        - docker
        - devtools
    - role: flatpak
      tags:
        - flatpak
    - dropbox
    - role: keybase
      tags:
        - keybase
