---
- name: Setup Fedora Workstation
  hosts: local
  become: yes

  roles:
    - role: setup
      tags:
        - setup
    - role: fish
      tags:
        - fish
    - role: power
      tags:
        - power
        - tlp
        - powertop
    - role: inputrc
      tags:
        - inputrc
    - role: elixir
      tags:
        - elixir
        - devtools
    - role: iosevka
      tags:
        - iosevka
        - fonts
        - devtools
    - role: gnome
      tags:
        - gnome
    - role: neovim
      tags:
        - nvim
        - neovim
        - devtools
    - role: tilix
      tags:
        - tilix
    - role: elasticsearch
      tags:
        - elasticsearch
        - devtools
    - role: asdf
      tags:
        - asdf
        - ruby
        - devtools
    - role: git
      tags:
        - git
        - devtools
    - role: devops
      tags:
        - devops
    - role: postgres
      tags:
        - db
        - devtools
        - postgres
    - role: flatpak
      tags:
        - flatpak
        - postman
        - slack
        - spotify
        - steam
    - dropbox
    - role: onepassword
      tags:
        - onepassword
