---
- name: Setup Fedora Workstation
  hosts: local
  become: yes

  roles:
    - role: setup
      tags:
        - setup
    - role: fish
      tags:
        - fish
    - role: power
      tags:
        - power
        - tlp
        - powertop
    - role: inputrc
      tags:
        - inputrc
    - role: gnome
      tags:
        - gnome
    - role: neovim
      tags:
        - nvim
        - neovim
        - devtools
    - role: asdf
      tags:
        - asdf
        - ruby
        - devtools
    - role: git
      tags:
        - git
        - devtools
    - role: devops
      tags:
        - devops
    - role: flatpak
      tags:
        - flatpak
        - postman
        - slack
        - spotify
        - steam
    - dropbox
    - role: kitty
      tags:
        - kitty
    - role: gog
      tags:
        - gog
        - games
