---
- name: Setup Fedora Workstation
  hosts: local
  become: yes

  roles:
    - setup
    - iosevka
    - gnome
    - neovim
    - elasticsearch
    - git
    - role: hashicorp
      tags: 
        - hashicorp
    - slack
    - flatpak
    - dropbox
