---
- name: Obtain Terraform version
  shell: "{{ terraform.bin_path }}/terraform --version | head -1 | sed 's/Terraform v//g'"
  ignore_errors: yes
  register: installed_terraform_version
  changed_when: false
  tags:
    - terraform

- name: Installed Terraform version
  debug:
    var: installed_terraform_version.stdout
    verbosity: 2
  tags:
    - terraform

- name: Install Terraform
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform.version }}/terraform_{{ terraform.version }}_linux_amd64.zip"
    dest: "{{ terraform.bin_path }}"
    remote_src: yes
    owner: root
    group: root
  when: installed_terraform_version.stdout != terraform.version
  tags:
    - terraform

- name: Add Google Cloud repository
  yum_repository:
    name: google-cloud-sdk
    description: Google Cloud SDK
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install DevOps tools
  dnf:
    name:
      - awscli
      - buildah
      - google-cloud-sdk
      - htop
      - kubectl
      - podman
      - sen
      - skopeo
    state: present
  tags:
    - aws
    - buildah
    - docker
    - k8s
    - kubernetes
    - podman
