---
- name: Install software for power management
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - tlp
    - powertop

- name: Start and enable tlp
  systemd:
    name: tlp
    enabled: yes
    state: started
