---
- name: Install software for power management
  dnf:
    name:
      - tlp
      - powertop
    state: present

- name: Start and enable tlp
  systemd:
    name: tlp
    enabled: yes
    state: started
