---
- name: Create iosevka directory
  file:
    path: /usr/local/share/fonts/iosevka
    owner: root
    group: root
    mode: 0755
    recurse: yes
    state: directory

- name: Extract iosevka pack
  unarchive:
    src: https://github.com/be5invis/Iosevka/releases/download/v1.13.3/iosevka-pack-1.13.3.zip
    dest: /usr/local/share/fonts/iosevka
    remote_src: yes
  register: iosevka_result

- name: Update fonts cache
  command: fc-cache -f -v
  when: iosevka_result|changed
