---
- name: Install flathub repo
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Remove filter from flathub repo
  shell: flatpak remote-modify flathub --no-filter
  ignore_errors: yes
  changed_when: false

- name: Install flatpak applications
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  with_items:
    - com.discordapp.Discord
    - com.github.tchx84.Flatseal
    - com.heroicgameslauncher.hgl
    - com.slack.Slack
    - com.spotify.Client
    - com.usebruno.Bruno
    - com.valvesoftware.Steam
    - com.zettlr.Zettlr
    - org.freedesktop.Platform//22.08
    - org.zotero.Zotero
    - us.zoom.Zoom
