---
- name: Install flatpak applications
  flatpak:
    name: "{{ item }}"
    state: present
  with_items:
    - org.freedesktop.Platform//18.08
    - com.discrodapp.Discord
    - com.getpostman.Postman
    - com.slack.Slack
    - com.spotify.Client
    - com.valvesoftware.Steam
