---
- name: Install flathub repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak applications
  flatpak:
    name: "{{ item }}"
    state: present
  with_items:
    - com.discrodapp.Discord
    - com.getpostman.Postman
    - com.github.tchx84.Flatseal
    - com.heroicgameslauncher.hgl
    - com.slack.Slack
    - com.spotify.Client
    - com.valvesoftware.Steam
    - com.zettlr.Zettlr
    - org.freedesktop.Platform//21.08
    - org.zotero.Zotero
    - us.zoom.Zoom
