---
- name: Install flathub repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak applications
  flatpak:
    name: "{{ item }}"
    state: present
  with_items:
    - org.freedesktop.Platform//21.08
    - com.discrodapp.Discord
    - com.getpostman.Postman
    - com.slack.Slack
    - com.spotify.Client
    - com.valvesoftware.Steam
