---
- name: Install flathub repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak applications
  flatpak:
    name: "{{ item }}"
    state: present
  with_items:
    - org.freedesktop.Platform//18.08
    - com.spotify.Client
    - net.openra.OpenRA
    - com.valvesoftware.Steam
