---
- name: Disable natural scrolling
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "false"
    state: present

- name: Swap caps lock with CTRL
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['ctrl:nocaps']"
    state: present

- name: Install Gnome extensions
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - gnome-shell-extension-do-not-disturb-button
