---
- name: Disable natural scrolling
  gsetting:
    user: jdudulski
    key: org.gnome.desktop.peripherals.touchpad.natural-scroll
    value: "false"

- name: Swap caps lock with CTRL
  gsetting: user=jdudulski
            key=org.gnome.desktop.input-sources.xkb-options
            value="['ctrl:nocaps']"

- name: Install Gnome extensions
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - gnome-shell-extension-do-not-disturb-button
