---
- name: Disable natural scrolling
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "false"
    state: present

- name: Swap caps lock with CTRL
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['ctrl:nocaps']"
    state: present

- name: Install Gnome extensions
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - gnome-shell-extension-do-not-disturb-button

- name: Enable do not disturb extension
  become_user: "{{ user }}"
  shell: gnome-shell-extension-tool --enable-extension=donotdisturb-button@nls1729
  register: enable_donotdisturb
  changed_when: >
    enable_donotdisturb.rc == 0 and ("'donotdisturb-button@nls1729' is now enabled." in enable_donotdisturb.stdout)
