---
- name: Remove redundant software
  dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - gnome-documents
    - gnome-shell-extension-alternate-tab
    - gnome-shell-extension-background-logo
    - gnome-shell-extension-launch-new-instance
    - gnome-shell-extension-places-menu
    - gnome-shell-extension-window-list

- name: Install gnome shell extensions
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - chrome-gnome-shell
    - gnome-shell-extension-pomodoro

- name: Enable lcdfilter
  file:
    src: /usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf
    path: /etc/fonts/conf.d/11-lcdfilter-default.conf
    state: link

- name: Disable natural scrolling
  become_user: "{{ ansible_user }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "false"
    state: present

- name: Swap caps lock with CTRL
  become_user: "{{ ansible_user }}"
  dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['ctrl:nocaps']"
    state: present

- name: Enable night light
  become_user: "{{ ansible_user }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"
    state: present

- name: Enable date in gnome clock
  become_user: "{{ ansible_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"
    state: present

- name: Set scaling factor better for HiDPi
  become_user: "{{ ansible_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/text-scaling-factor"
    value: "1.0"
    state: present

- name: Set antialiasing for LCD
  become_user: "{{ ansible_user }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/xsettings/antialiasing"
    value: "'rgba'"
    state: present

- name: Set Iosevka as terminal font
  become_user: "{{ ansible_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/monospace-font-name"
    value: "'Iosevka Term 10'"
    state: present

- name: Set favorite applications
  become_user: "{{ ansible_user }}"
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['firefox.desktop', 'slack.desktop', 'org.gnome.Nautilus.desktop', 'com.gexperts.Tilix.desktop', 'slack.desktop', 'com.spotify.Client.desktop']"

- name: Install Gnome extensions
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - gnome-shell-extension-do-not-disturb-button

- name: Enable do not disturb extension
  become_user: "{{ ansible_user }}"
  shell: gnome-shell-extension-tool --enable-extension=donotdisturb-button@nls1729
  register: enable_donotdisturb
  failed_when: >
    enable_donotdisturb.rc > 0 and ("'donotdisturb-button@nls1729' is already enabled." not in enable_donotdisturb.stderr)
  changed_when: >
    enable_donotdisturb.rc == 0 and ("'donotdisturb-button@nls1729' is now enabled." in enable_donotdisturb.stdout)

- name: Create local backgrounds directory
  file:
    path: /usr/local/share/backgrounds
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Copy backgrounds
  copy:
    src: "{{ background_name }}"
    dest: "{{ backgrounds_path }}"
    owner: root
    group: root

- name: Set background
  become_user: "{{ ansible_user }}"
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file://{{ backgrounds_path }}/{{ background_name }}'"
    state: present
