---
- name: Generate git config directories
  file:
    path: "/home/{{ ansible_user }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
    state: directory
  with_items:
    - .config/git
    - .git_template
    - .git_template/hooks

- name: Copy git template hooks
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/.git_template/hooks"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  with_items:
    - ctags
    - post-checkout
    - post-commit
    - post-merge

- name: Generate git config
  template:
    src: gitconfig.j2
    dest: "/home/{{ ansible_user }}/.gitconfig"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Generate global git ignore
  template:
    src: gitignore_global.j2
    dest: "/home/{{ ansible_user }}/.config/git/ignore"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
