---
- name: Generate git config
  template:
    src: gitconfig.j2
    dest: "/home/{{ user }}/.gitconfig"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Generate global git ignore
  template:
    src: gitignore_global.j2
    dest: "/home/{{ user }}/.gitignore_global"
    owner: "{{ user }}"
    group: "{{ user }}"
