---
- name: Install Dropbox
  dnf:
    name: nautilus-dropbox
    state: present

- name: Install Dropbox daemon
  become_user: "{{ user }}"
  shell: dropbox start --install
  register: dropbox_start_result
  changed_when: >
    dropbox_start_result.rc == 0 and ("Dropbox is already running!" not in dropbox_start_result.stdout)
