---
- name: Install tilix
  dnf:
    name: tilix
    state: present

- name: Create tilix schemes directory
  file:
    path: "/home/{{ ansible_user }}/.config/tilix/schemes"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
    state: directory

- name: Generate gruvbox light scheme for tilix
  template:
    src: gruvbox-light.json.j2
    dest: "/home/{{ ansible_user }}/.config/tilix/schemes/gruvbox-light.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
