---
- name: Install RPM Fusion repositories
  dnf:
    name: "https://download1.rpmfusion.org/{{ item }}/fedora/rpmfusion-{{ item }}-release-{{ ansible_distribution_version }}.noarch.rpm"
    state: present
  with_items:
    - free
    - nonfree

- name: Install dependencies
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - python-gpgme
    - python2-psutil

- name: Install software
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - ImageMagick
    - ImageMagick-devel
    - asciinema
    - darktable
    - entr
    - fish
    - freetype-freeworld
    - fzf
    - gimp
    - gnome-todo
    - jq
    - keepassxc
    - kodi
    - lm_sensors
    - mongo-tools
    - mongodb
    - mongodb-server
    - nmap
    - redis
    - qt5-qtwebkit-devel
    - ripgrep
    - seafile
    - seafile-client
    - snapd
    - sqlite
    - sqlite-devel
    - unrar
    - xclip

- name: Configure user
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/fish
    groups:
      - docker
      - wheel

- name: Create functions fish directory
  file:
    path: "/home/{{ ansible_user }}/.config/fish/functions"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: 0755

- name: Configure fish shell
  template:
    src: config.fish.j2
    dest: "/home/{{ ansible_user }}/.config/fish/config.fish"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Enable fish user bindings
  template:
    src: fish_user_key_bindings.fish.j2
    dest: "/home/{{ ansible_user }}/.config/fish/functions/fish_user_key_bindings.fish"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Disable bluetooth
  systemd:
    name: bluetooth
    state: stopped
    enabled: false
