---
- name: Install dependencies
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - python-gpgme
    - python2-psutil

- name: Install software
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - keepassxc
    - tilix
