---
- name: Install RPM Fusion repositories
  dnf:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Install dependencies
  dnf:
    name:
      - python3-psutil
      - python3-devel
    state: present

- name: Install software
  dnf:
    name:
      - ImageMagick
      - ImageMagick-devel
      - asciinema
      - bat
      - darktable
      - direnv
      - entr
      - fd-find
      - freetype-freeworld
      - fzf
      - gimp
      - gtk-murrine-engine
      - httpie
      - inotify-tools
      - joplin
      - jq
      - keepassxc
      - kodi
      - lm_sensors
      - nmap
      - postgresql
      - postgresql-devel
      - pwgen
      - qt5-qtwebkit-devel
      - ripgrep
      - seafile
      - seafile-client
      - snapd
      - sqlite
      - sqlite-devel
      - unrar
      - xclip
    state: present

- name: Configure user
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/fish
    groups:
      - wheel
