---
- name: Install neovim
  dnf:
    name:
      - neovim
    state: present

- name: Install ctags
  snap:
    name:
      - universal-ctags
    state: present

- name: Generate local neovim config directory
  file:
    path: "/home/{{ ansible_user }}/.config/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  with_items:
    - nvim
    - nvim/autoload
    - nvim/plugged
    - nvim/ftplugin

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ ansible_user }}/.config/nvim/autoload/plug.vim"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Generate neovim config
  template:
    src: init.vim.j2
    dest: "/home/{{ ansible_user }}/.config/nvim/init.vim"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Generate file type plugins
  template:
    src: "ftplugin/{{ item }}.vim.j2"
    dest: "/home/{{ ansible_user }}/.config/nvim/ftplugin/{{ item }}.vim"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  with_items:
    - elixir
    - ruby
