---
- name: Enable universal-ctags copr
  become: yes
  shell: dnf copr --assumeyes enable thindil/universal-ctags
  creates: /etc/yum.repos.d/_copr_thindil-universal-ctags.repo

- name: Install neovim and ctags
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - neovim
    - universal-ctags

- name: Generate local neovim config directory
  file:
    path: "/etc/xdg/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - nvim
    - nvim/autoload
    - nvim/plugged

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /etc/xdg/nvim/autoload/plug.vim
    owner: root
    group: root
    mode: 0644

- name: Generate neovim config
  template:
    src: init.vim.j2
    dest: /etc/xdg/nvim/init.vim
    owner: root
    group: root
    mode: 0644
