---
- name: Install neovim
  dnf:
    name:
      - neovim
    state: present

- name: Install ctags
  snap:
    name:
      - universal-ctags
    state: present

- name: Generate local neovim config directory
  file:
    path: "/home/{{ ansible_user }}/.config/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  with_items:
    - nvim
    - nvim/lua
    - nvim/lua/core
    - nvim/lua/plugins

- name: Generate neovim config
  template:
    src: init.lua.j2
    dest: "/home/{{ ansible_user }}/.config/nvim/init.lua"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Generate lua config files
  template:
    src: "lua/{{ item }}.lua.j2"
    dest: "/home/{{ ansible_user }}/.config/nvim/lua/{{ item }}.lua"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  with_items:
    - "plugins/lazy-config"
    - "core/mappings"
    - "plugins/mason-config"
    - "plugins/cmp-config"
    - "plugins/null-config"
    - "plugins/fugitive-config"
    - "plugins/lualine-config"
    - "plugins/rails-config"
    - "plugins/projectionist-config"
    - "plugins/telescope-config"
